runtime: python27
api_version: 1
threadsafe: true

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest

automatic_scaling:
  max_idle_instances: 2

handlers:
#TODO: reconcile these
- url: /
  script: main.app

- url: /index.html
  script: main.app

- url: /(.*)
  static_files: www/\1
  upload: www/(.*)

