runtime: python27
api_version: 1
threadsafe: true

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest

automatic_scaling:
  max_idle_instances: 2

handlers:
- url: /styles
  static_dir: styles

- url: /js
  static_dir: js

- url: /images
  static_dir: images

- url: /.*
  script: main.app